import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';
import { Download, FolderGit2, GitBranch, FileText, GitMerge } from 'lucide-react';
import { Section } from './Section';

const steps = [
  {
    icon: Download,
    title: 'Install the GitHub App',
    description: 'One-click installation from GitHub Marketplace',
  },
  {
    icon: FolderGit2,
    title: 'Select Repositories',
    description: 'Choose which repos to enable',
  },
  {
    icon: GitBranch,
    title: 'Push Your Code',
    description: 'Make any code change and push to your default branch',
  },
  {
    icon: FileText,
    title: 'Get Comprehensive Docs',
    description: 'AI analyzes your code and creates a PR with documentation',
  },
  {
    icon: GitMerge,
    title: 'You review and merge',
    description: 'Full control stays with you',
  },
];

export function HowItWorks() {
  return (
    <Section id="how-it-works" className="bg-gradient-to-b from-black/30 to-black/50">
      <div className="text-center mb-16">
        <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
          How it works
        </h2>
        <p className="text-xl text-gray-400">
          From installation to documentation in 5 simple steps
        </p>
      </div>

      <div className="max-w-4xl mx-auto">
        {steps.map((step, index) => {
          const [ref, inView] = useInView({
            triggerOnce: true,
            threshold: 0.3,
          });

          return (
            <motion.div
              key={index}
              ref={ref}
              initial={{ opacity: 0, x: -50 }}
              animate={inView ? { opacity: 1, x: 0 } : {}}
              transition={{ duration: 0.6, delay: index * 0.2 }}
              className="relative flex gap-8 mb-12 last:mb-0"
            >
              {index < steps.length - 1 && (
                <div className="absolute left-8 top-20 bottom-0 w-0.5 bg-gradient-to-b from-purple-500 to-transparent" />
              )}

              <div className="relative z-10 flex-shrink-0">
                <div className="w-16 h-16 rounded-full bg-gradient-to-br from-purple-600 to-blue-600 flex items-center justify-center shadow-lg shadow-purple-500/50">
                  <step.icon className="w-8 h-8 text-white" />
                </div>
              </div>

              <div className="flex-1 pt-3">
                <h3 className="text-2xl font-bold text-white mb-2">{step.title}</h3>
                <p className="text-gray-400 text-lg">{step.description}</p>

                {index === 0 && (
                  <div className="mt-4 bg-white/5 backdrop-blur-lg border border-white/10 rounded-lg p-4">
                    <div className="text-sm text-gray-400">GitHub Marketplace</div>
                    <div className="text-purple-400 font-mono text-sm mt-2">github.com/apps/document-gen</div>
                  </div>
                )}

                {index === 2 && (
                  <div className="mt-4 bg-black/50 border border-white/10 rounded-lg p-4 font-mono text-sm">
                    <div className="text-green-400">$ git push origin main</div>
                    <div className="text-gray-500 mt-1">Pushing to github.com/user/repo.git...</div>
                  </div>
                )}

                {index === 3 && (
                  <div className="mt-4 bg-white/5 backdrop-blur-lg border border-white/10 rounded-lg p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                      <span className="text-sm text-gray-300">Pull Request #123</span>
                    </div>
                    <div className="text-white font-semibold">Update documentation</div>
                    <div className="text-gray-400 text-sm mt-1">Generated by Document-Gen AI</div>
                  </div>
                )}
              </div>
            </motion.div>
          );
        })}
      </div>
    </Section>
  );
}
